safe:             false
port:             4000
baseurl:          /
url:              https://www.fontawesomecheatsheet.com
title:            Fontawesome Cheatsheet
twitter_username: WouterSteen
github_username:  WouterSteen
description:      Font awesome Cheat sheet
plugins:
  - jekyll-sitemap
